name: Print Even Numbers
'on':
  push:
    branches:
      - main
jobs:
  print-even-numbers:
    runs-on: ubuntu-latest
    steps:
      - name: Print Even Numbers
        run: |
          for num in range(1, 101):
            if num % 2 == 0:
              echo $num
